apiVersion: v1
kind: Service
metadata:
  name: gym-membership-tracker-service
  labels:
    app: gym-membership-tracker
spec:
  selector:
    app: gym-membership-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
