apiVersion: v1
kind: Service
metadata:
  name: gym-membership-tracker-service
  namespace: default
  labels:
    app: gym-membership-tracker
spec:
  type: ClusterIP
  selector:
    app: gym-membership-tracker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
